export const types = {
    SET_SEARCH_PROPERTIES: "SET_SEARCH_PROPERTIES",
    SET_PROPERTIES: "SET_PROPERTIES",
    SET_SEARCH_FORM:"SET_SEARCH_FORM",
    LOGIN_SUCCESS : "LOGIN_SUCCESS",
    LOGIN_FAILED: "LOGIN_FAILED",
    LOGOUT: "LOGOUT",

};

    
